language: c++

branches:
  only:
    - master

before_install:
  - sudo apt-get install debhelper autotools-dev autoconf-archive pkg-config libc6-dev libcanberra-dev libcap-dev libclamav-dev  libgtk2.0-dev libmount-dev libnotify-dev

install:
  - true

script: 
  - ./autogen.sh
  - ./configure
  - make
  - make check

